version: "3.8"
services:

  Review:
    container_name: Review
    build: .\Review
    ports:
      - "8089:8089"
    hostname: review
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql_2:3306/review?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    image: "review"  # Change to lowercase
    depends_on:
      - Eureka
      - docker-mysql_2

  docker-mysql_2:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: " "
      MYSQL_DATABASE: review
    ports:
      - 3308:3306

  Eureka:
    container_name: Eureka
    build: .\Eureka
    ports:
      - "8761:8761"
    hostname: eureka
    image: "eureka"  # Change to lowercase
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
